shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HOME, name= 'index'),
    path('base/', views.BASE, name='base'),
    path('products/', views.PRODUCT, name='product'),
    path('search/', views.SEARCH, name='search'),
    path('product/<str:id>', views.PRODUCT_DETAIL_PAGE, name='product_details'),
    
    path('contact/', views.Contact_Page, name='contact'),
    
    path('register/',views.HandleRegister, name='register'),
    path('login/',views.HandleLogin, name='login'),
    path('logout/',views.HandleLogout, name='logout'),


] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)




# For Admin Panel Update
admin.site.site_header = 'Mayu Shop'                    
admin.site.index_title = 'Mayu Shop Field'                 
admin.site.site_title = 'Mayu Shop Admin Panel' 

store_app/models.py
# from datetime import timezone
from django.utils import timezone

from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Color(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Filter_Price(models.Model):
    FILTER_PRICE = (
        ('1000 To 10000', '1000 To 10000'),
        ('10000 To 20000', '10000 To 20000'),
        ('20000 To 30000', '20000 To 30000'),
        ('30000 To 40000', '30000 To 40000'),
        ('40000 To 50000', '40000 To 50000'),
        ('100000 To 500000', '100000 To 500000'),
    )

    price = models.CharField(choices=FILTER_PRICE, max_length=60)

    def __str__(self):
        return self.price


class Product(models.Model):
    CONDITION = (
        ('New', 'New'),
        ('Old', 'Old')
    )
    STOCK = (
        ('IN STOCK', 'IN STOCK'),
        ('OUT OF STOCK', 'OUT OF STOCK')
    )
    STATUS = (
        ('Publish', 'Publish'),
        ('Draft', 'Draft')
    )

    unique_id = models.CharField(unique=True, max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to='Product_images/img')
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    condition = models.CharField(choices=CONDITION, max_length=100)
    information = RichTextField(null=True)
    description = RichTextField(null=True)
    stock = models.CharField(choices=STOCK, max_length=200)
    status = models.CharField(choices=STATUS, max_length=200)
    created_date = models.DateTimeField(default=timezone.now)

    categories = models.ForeignKey(Categories, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    filter_price = models.ForeignKey(Filter_Price, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if self.unique_id is None and self.created_date and self.id:
            self.unique_id = self.created_date.strftime('18%Y%m%d23') + str(self.id)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Images(models.Model):
    image = models.ImageField(upload_to='Product_images/img')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Tag(models.Model):
    name = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

class Contact_us(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=300)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.email

templates/main/contact.html
{% extends 'main/base.html' %}
{% block content %}

<!-- Contact Area Start -->
<div class="contact-area">
    <div class="container">
        <div class="contact-wrapper">
            <div class="row">
                <div class="col-12">
                    <div class="contact-form">
                        <div class="contact-title mb-30">
                            <h2 class="title">Send A Quest</h2>
                        </div>
                        <form class="contact-form-style"  action="/contact/" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-6">
                                    <input name="name" placeholder="Name*" type="text" />
                                </div>
                                <div class="col-lg-6">
                                    <input name="email" placeholder="Email*" type="email" />
                                </div>
                                <div class="col-lg-12">
                                    <input name="subject" placeholder="Subject*" type="text" />
                                </div>
                                <div class="col-lg-12 text-center">
                                    <textarea name="message" placeholder="Your Message*"></textarea>
                                    <button class="btn btn-primary" type="submit">Send Message</button>
                                </div>
                            </div>
                        </form>
                        <p class="form-messege"></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="contact-info">
                        <div class="single-contact">
                            <div class="icon-box">
                                <img src="assets/images/icons/contact-1.png" alt="">
                            </div>
                            <div class="info-box">
                                <h5 class="title">Address</h5>
                                <p>Your address goes here. <br>
                                123 Your Location</p>
                            </div>
                        </div>
                        <div class="single-contact">
                            <div class="icon-box">
                                <img src="assets/images/icons/contact-2.png" alt="">
                            </div>
                            <div class="info-box">
                                <h5 class="title">Phone No</h5>
                                <p><a href="tel:0123456789">+012 345 67 89</a></p>
                                <p><a href="tel:0123456789">+012 345 67 89</a></p>
                            </div>
                        </div>
                        <div class="single-contact m-0">
                            <div class="icon-box">
                                <img src="assets/images/icons/contact-3.png" alt="">
                            </div>
                            <div class="info-box">
                                <h5 class="title">Email/Web</h5>
                                <p><a href="mailto:demo@example.com">demo@example.com</a></p>
                                <p><a href="https://www.example.com/">www.example.com</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact Area End -->
 <!-- map Area Start -->
 <div class="contact-map">
    <div id="mapid">
        <div class="mapouter">
            <div class="gmap_canvas">
                <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=121%20King%20St%2C%20Melbourne%20VIC%203000%2C%20Australia&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed"></iframe>
                <a href="https://sites.google.com/view/maps-api-v2/mapv2"></a>
            </div>
        </div>
    </div>
</div>
<!-- map Area End -->


{% endblock %}

templates/main/product_single.html
{% extends 'main/base.html' %}
{% block content %}

 <!-- Product Details Area Start -->
 <div class="product-details-area pt-100px pb-100px">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-12 col-xs-12 mb-lm-30px mb-md-30px mb-sm-30px">
                <!-- Swiper -->
                <div class="swiper-container zoom-top">
                    <div class="swiper-wrapper">
                        {% for i in prod.images_set.all%}
                        <div class="swiper-slide">
                            <img class="img-responsive m-auto" src="/{{i.image}}" alt="">
                            <a class="venobox full-preview" data-gall="myGallery" href="/{{i.image}}">
                                <i class="fa fa-arrows-alt" aria-hidden="true"></i>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="swiper-container mt-20px zoom-thumbs slider-nav-style-1 small-nav">
                    <div class="swiper-wrapper">
                        {% for i in prod.images_set.all%}
                        <div class="swiper-slide">
                            <img class="img-responsive m-auto" src="/{{i.image}}" alt="">
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Add Arrows -->
                    <div class="swiper-buttons">
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-sm-12 col-xs-12" data-aos="fade-up" data-aos-delay="200">
                <div class="product-details-content quickview-content ml-25px">
                    <h2>{{prod.name|truncatewords:40}}</h2>
                    <div class="pricing-meta">
                        <ul class="d-flex">
                            <li class="new-price">₹{{prod.price}}</li>
                        </ul>
                    </div>
                    <div class="pro-details-rating-wrap">
                        <div class="rating-product">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <span class="read-review"><a class="reviews" href="#">(5 Customer Review)</a></span>
                    </div>
                    <p class="mt-30px">{{prod.description | safe}}</p>
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <span>SKU:</span>
                        <ul class="d-flex">
                            <li>
                                <a href="#">Ch-256xl</a>
                            </li>
                        </ul>
                    </div>
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <span>Categories: </span>
                        <ul class="d-flex">
                            <a href="#"> {{prod.categories}} </a>
                        </ul>
                    </div>
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <span>Tags: </span>
                        <ul class="d-flex">
                            <li>
                            {% for i in prod.tag_set.all%}
                            <a href="#">{{i.name}}, </a>
                            {% endfor %}
                            </li>
                        </ul>
                    </div>
                    <div class="pro-details-quality">
                        <div class="cart-plus-minus">
                            <input class="cart-plus-minus-box" type="text" name="qtybutton" value="1" />
                        </div>
                        <div class="pro-details-cart">
                            <button class="add-cart"> Add To
                                Cart</button>
                        </div>
                        <div class="pro-details-compare-wishlist pro-details-wishlist ">
                            <a href="wishlist.html"><i class="pe-7s-like"></i></a>
                        </div>
                        <div class="pro-details-compare-wishlist pro-details-wishlist ">
                            <a href="compare.html"><i class="pe-7s-refresh-2"></i></a>
                        </div>
                    </div>
                </div>
                <!-- product details description area start -->
                <div class="description-review-wrapper">
                    <div class="description-review-topbar nav">
                        <button data-bs-toggle="tab" data-bs-target="#des-details2">Information</button>
                        <button class="active" data-bs-toggle="tab" data-bs-target="#des-details1">Description</button>
                        <button data-bs-toggle="tab" data-bs-target="#des-details3">Reviews (02)</button>
                    </div>
                    <div class="tab-content description-review-bottom">
                        <div id="des-details2" class="tab-pane">
                            <div class="product-anotherinfo-wrapper text-start">
                                <ul>
                                    <li>{{prod.information | safe}}</li>
                                 </ul>
                            </div>
                        </div>
                        <div id="des-details1" class="tab-pane active">
                            <div class="product-description-wrapper">
                                <p>{{prod.description | safe}}</p>
                            </div>
                        </div>
                        <div id="des-details3" class="tab-pane">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="review-wrapper">
                                        <div class="single-review">
                                            <div class="review-img">
                                                <img src="assets/images/review-image/1.png" alt="" />
                                            </div>
                                            <div class="review-content">
                                                <div class="review-top-wrap">
                                                    <div class="review-left">
                                                        <div class="review-name">
                                                            <h4>White Lewis</h4>
                                                        </div>
                                                        <div class="rating-product">
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                        </div>
                                                    </div>
                                                    <div class="review-left">
                                                        <a href="#">Reply</a>
                                                    </div>
                                                </div>
                                                <div class="review-bottom">
                                                    <p>
                                                        Vestibulum ante ipsum primis aucibus orci luctustrices posuere
                                                        cubilia Curae Suspendisse viverra ed viverra. Mauris ullarper
                                                        euismod vehicula. Phasellus quam nisi, congue id nulla.
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="single-review child-review">
                                            <div class="review-img">
                                                <img src="assets/images/review-image/2.png" alt="" />
                                            </div>
                                            <div class="review-content">
                                                <div class="review-top-wrap">
                                                    <div class="review-left">
                                                        <div class="review-name">
                                                            <h4>White Lewis</h4>
                                                        </div>
                                                        <div class="rating-product">
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                        </div>
                                                    </div>
                                                    <div class="review-left">
                                                        <a href="#">Reply</a>
                                                    </div>
                                                </div>
                                                <div class="review-bottom">
                                                    <p>Vestibulum ante ipsum primis aucibus orci luctustrices posuere
                                                        cubilia Curae Sus pen disse viverra ed viverra. Mauris ullarper
                                                        euismod vehicula.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="ratting-form-wrapper pl-50">
                                        <h3>Add a Review</h3>
                                        <div class="ratting-form">
                                            <form action="#">
                                                <div class="star-box">
                                                    <span>Your rating:</span>
                                                    <div class="rating-product">
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="rating-form-style">
                                                            <input placeholder="Name" type="text" />
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="rating-form-style">
                                                            <input placeholder="Email" type="email" />
                                                        </div>
                                                    </div>
                                                    <div class="col-md-12">
                                                        <div class="rating-form-style form-submit">
                                                            <textarea name="Your Review" placeholder="Message"></textarea>
                                                            <button class="btn btn-primary btn-hover-color-primary " type="submit" value="Submit">Submit</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- product details description area end -->
            </div>
        </div>
    </div>
</div>
<!-- Product Area Start -->

{% endblock %}

templates/main/search.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <br>
    <h2>Search Result : </h2>
    {% if product|length < 1 %}
    <p> No Product Found</p>
    {% endif %}
</div>
<!-- Shop Page Start  -->
<div class="shop-category-area pt-100px pb-100px">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <div class="shop-bottom-area">
                    <!-- Tab Content Area Start -->
                    <div class="row">
                        <div class="col">
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="shop-grid">
                                    <div class="row mb-n-30px">
                                        <!--                                        Product Start Here -->
                                        {% for pro in product %}
                                        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-xs-6 mb-30px">
                                            <!-- Single Prodect -->
                                            <div class="product">
                                                        <span class="badges">
                                                        <span class="new">{{pro.condition}}</span>
                                                        </span>
                                                <div class="thumb">
                                                    <a href="single-product.html" class="image">
                                                        <img src="/{{pro.image}}" alt="Product"/>
                                                        <img class="hover-image"
                                                             src="/{{pro.image}}" alt="Product"/>
                                                    </a>
                                                </div>
                                                <div class="content">
                                                    <span class="category"><a href="#">{{pro.categories}}</a></span>
                                                    <h5 class="title"><a href="single-product.html">
                                                        {{pro.name | truncatewords:8 }}
                                                    </a>
                                                    </h5>
                                                    <span class="price">
                                                            <span class="new">₹{{pro.price}}</span>
                                                            </span>
                                                </div>
                                                <div class="actions">
                                                    <button title="Add To Cart" class="action add-to-cart"
                                                            data-bs-toggle="modal" data-bs-target="#exampleModal-Cart">
                                                        <i
                                                                class="pe-7s-shopbag"></i></button>
                                                    <button class="action wishlist" title="Wishlist"
                                                            data-bs-toggle="modal"
                                                            data-bs-target="#exampleModal-Wishlist"><i
                                                            class="pe-7s-like"></i></button>
                                                    <button class="action quickview" data-link-action="quickview"
                                                            title="Quick view" data-bs-toggle="modal"
                                                            data-bs-target="#exampleModal-{{forloop.counter}}"><i
                                                            class="pe-7s-look"></i>
                                                    </button>
                                                    <button class="action compare" title="Compare"
                                                            data-bs-toggle="modal"
                                                            data-bs-target="#exampleModal-Compare"><i
                                                            class="pe-7s-refresh-2"></i></button>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}

                                        <!--                                        End Product -->


                                        {% endblock %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>